#!/usr/bin/env python

from buildsystem.targetrules import TargetRules, TargetType

class SandboxTargetRules(TargetRules):
    def __init__(self):
        super(SandboxTargetRules, self).__init__()
        self.target_type = TargetType.PROGRAM
        self.public_dependencies = ["src/modules/mylib/mylib.lib"]

Import('env')  
env_sandbox = env.Clone()
env.setup_target(SandboxTargetRules())