#!/usr/bin/env python

from buildsystem.targetrules import TargetRules, setup_target

class SandboxTargetRules(TargetRules):
    def __init__(self):
        super(SandboxTargetRules, self).__init__()

Import('env')  
setup_target(env, SandboxTargetRules())