#!/usr/bin/env python

from buildsystem.targetrules import TargetRules, TargetType
import os

class MylibTargetRules(TargetRules):
    def __init__(self):
        super(MylibTargetRules, self).__init__()
        self.target_type = TargetType.MODULE

        self.intermediate_path = os.path.join( os.path.abspath('.'), "Intermediate")
        self.public_include_paths = [os.path.join( os.path.abspath('.'), "Source/Public")]
        self.private_include_paths = [os.path.join( os.path.abspath('.'), "Source/Private")]
        self.source_paths = ["Source/Private", "Source/Public"]

Import('env')
env_mylib = env.Clone()
env.setup_target(MylibTargetRules())