#pragma once

// From glfw.h

#define SPARK_MOUSE_BUTTON_1         0
#define SPARK_MOUSE_BUTTON_2         1
#define SPARK_MOUSE_BUTTON_3         2
#define SPARK_MOUSE_BUTTON_4         3
#define SPARK_MOUSE_BUTTON_5         4
#define SPARK_MOUSE_BUTTON_6         5
#define SPARK_MOUSE_BUTTON_7         6
#define SPARK_MOUSE_BUTTON_8         7
#define SPARK_MOUSE_BUTTON_LAST      SPARK_MOUSE_BUTTON_8
#define SPARK_MOUSE_BUTTON_LEFT      SPARK_MOUSE_BUTTON_1
#define SPARK_MOUSE_BUTTON_RIGHT     SPARK_MOUSE_BUTTON_2
#define SPARK_MOUSE_BUTTON_MIDDLE    SPARK_MOUSE_BUTTON_3