#!/usr/bin/env python

from buildsystem.targetrules import TargetRules, TargetType

class SparkengineTargetRules(TargetRules):
    def __init__(self):
        super(SparkengineTargetRules, self).__init__()

Import('env')
env.setup_target(SparkengineTargetRules())